"""
Copyright (c) 2021 Mauro Marini

Permission is hereby granted, free of charge, to any person
obtaining a copy of this software and associated documentation
files (the "Software"), to deal in the Software without
restriction, including without limitation the rights to use,
copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following
conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
OTHER DEALINGS IN THE SOFTWARE.
"""
import random

from docplex.mp.model import Model

import conf


class MaximumFlowSolver:
    """
    Maximum Flow solver
    """

    t_nodes = []

    def __init__(self, solution_df, range_nodes, s=0):
        """
        Constructor
        :param solution_df: the solution of the continuous relaxation (pd dataframe)
        :param range_nodes: an iterator from 0 to #nodes-1
        :param s: the starting node
        """
        assert len(MaximumFlowSolver.t_nodes) > 0
        self.__s = s
        self.__t = MaximumFlowSolver.t_nodes.pop(0)
        self.__crate_max_flow_model(range_nodes)
        self.__set_transhipment_for_all_nodes(range_nodes)
        self.__set_capacity_constraints(solution_df)

    def __set_capacity_constraints(self, solution_df):
        """
        Get capacities from the continuous relaxation solution and set it as constraints of the current model
        :param solution_df: the solution of the continuous relaxation (pd dataframe)
        :return:
        """
        for _, r in solution_df.iterrows():
            if conf.VERBOSE:
                print('start: ' + str(r['start']) + ', end: ' + str(r['end']) + ', value: ' + str(r['value']))
            self.__model.add_constraint(self.__x[r['start'], r['end']] <= r['value'])

    def __set_transhipment_for_all_nodes(self, range_nodes):
        """
        Set b(v) = 0 for all v in V
        :param range_nodes: an iterator from 0 to #nodes-1
        :return:
        """
        [self.__model.add_constraint(self.__model.sum([
            - self.__model.sum(self.__x[j, i] if i != j else 0 for j in range_nodes),
            self.__model.sum(self.__x[i, j] if i != j else 0 for j in range_nodes)
        ]) == 0) for i in range_nodes]
        [self.__model.add_constraint(self.__x[i, i] == 0) for i in range_nodes]

    def __crate_max_flow_model(self, range_nodes):
        """
        Create max flow model
        :param range_nodes: an iterator from 0 to #nodes-1
        :return:
        """
        self.__model = Model(name='max_flow_from_' + str(self.__s) + '_to_' + str(self.__t), log_output=True)
        self.__x = self.__model.continuous_var_matrix(range_nodes, range_nodes)
        if conf.VERBOSE:
            print(self.__model.name + '\ts: ' + str(self.__s) + '\tt: ' + str(self.__t))
        self.__model.maximize(1 * self.__x[self.__t, self.__s])

    def solve_max_flow(self):
        """
        Solve max flow
        :return: the solution of the max flow problem
        """
        solution = self.__model.solve()
        if conf.VERBOSE:
            self.__model.report()
        return solution

    def export_constraint(self):
        """
        Export constraint generated by max flow
        :return:
        """